# Welcome to the AntiPub configuration. To get started you may either:
# (A) run the plugin as-is, or (B) change values as instructed.

Global:
  # More information about regular expressions: http://docs.oracle.com/javase/tutorial/essential/regex/
  custom-filters:
    - "\\b0*(2(5[0-5]|[0-4]\\d)|1?\\d{1,2})(\\.0*(2(5[0-5]|[0-4]\\d)|1?\\d{1,2})){3}\\b"
  
  # The custom filter override will ignore the built-in filters and only
  # use the regex that you specify.
  custom-filter-override: false

  # Overrides the separate protocol logging and logs all protocols.
  log-alerts: true

  # A global setting to display alert logging for all protocols.
  log-display: true
  
# IPv4 or Internet Protocol v4 is the common protocol for IP addresses.
IPv4:
  # To (dis)allow IP addresses in chat.
  block-protocol: true
  
  # Exemptions will supersede any filters in place, no matter the
  # permission set. Regex's are not currently supported. Sorry!
  exemptions:
    - 192.168.1.1
  # Note: Quotations aren't required for the value.
  
  # Notifies the user they have posted blocked content.
  user-alert: true
  user-notification: "<user>, posting of IP's is not allowed."
  
  # Notifies administrators and mods of blocked content.
  # (requires antipub.mod, or antipub.*)
  admin-alert: true
  admin-notification: "<user>@<ip>.<hostname> attempted: <message>"

  # Performs an action based upon the amount of times a user has been notified.
  user-attempts: 3
  action: /ban <user>

  # Logs each alert into the specified database in Bukkit.yml.
  # The global variable 'global-log-alert' overrides this value.
  log-alert: true


# URL (uniform resource locator) protocol often used in web browsers.
URL:
  # To (dis)allow the URL protocol in chat.
  block-protocol: true
  
  # Exemptions will supersede any filters in place, no matter the
  # permission set. Regex's are not currently supported. Sorry!
  exemptions:
    - google.com
  # Note: Quotations aren't required for the value.
  
  # Notifies the user they have posted blocked content.
  user-alert: true
  user-notification: "<user>, posting of URL's is not allowed."
  
  # Notifies administrators and mods of blocked content.
  # (requires antipub.mod, or antipub.*)
  admin-alert: true
  admin-notification: "<user>@<ip>.<hostname> attempted: <message>"

  # Performs an action based upon the amount of times a user has been notified.
  user-attempts: 3
  action: /ban <user>

  # Logs each alert into the specified database in Bukkit.yml.
  # The global variable 'global-log-alert' overrides this value.
  log-alert: true