name: AntiPub
main: com.wolfy9247.AntiPub.AntiPub
version: ${project.version}
description: >
             AntiPub - a light-weight, effective plugin dedicated to blocking spam.
Author: Wolfy9247
permissions:
    antipub:
      description: Permission to bypass posting IPv4 addresses within the chat.
      children:
         antipub.*: true
         antipub.admin: true
      default: op
    antipub.admin:
      children:
         antipub.mod: true
         antipub.reload: true
         antipub.toggle.*: true
         antipub.addx: true
         antipub.remx: true

    antipub.mod:
      children:
         antipub.bypass: true
         antipub.notify: true
         antipub.help: true
commands:
    ap:
      aliases: [antipub]
      permission: antipub.mod
      usage: /ap <[help]|[reload]|[toggle]> <[IPv4|URL]> <[on|off]>
