name: AntiPub
main: main.java.com.wolfy9247.AntiPub.AntiPub
version: ${project.version}
description: >
             AntiPub - For all your anti-publicity needs! 
Author: Wolfy9247
permissions:
    antipub:
      description: Permission to bypass posting IPv4 addresses within the chat. 
      children:
         antipub.*: true
         antipub.admin: true
      default: op
    antipub.admin:
      children:
         antipub.mod: true
         antipub.reload: true
    antipub.mod:
      children:
         antipub.bypass: true
         antipub.notify: true
commands:
    ap:
      aliases: [antipub]
      permission: antipub.mod
      usage: /AP <help|set> <IPv4|Domains> <?args>
